// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/afs/cern.ch/work/h/htong/ZpZHllbb_13TeV/uncertainties/pdfScale.zjets/ele/./toyMC_ele.C";

#endif
